name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  firstworkflowjob:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: run bash command
        run: echo "Mo First workflow"
        shell: bash

